In [1]:
import pandas as pd
import numpy as np
import copy as cp
import darc_core
import pickle
import sys
import hashlib as hs
import base64 as b64
import os
import random as rd
import datetime as dt
from darc_core.metrics import Metrics
from darc_core.utils import M_COL, T_COL, T_COL_IT, NB_GUESS, SIZE_POOL
from darc_core.preprocessing import round1_preprocessing
from darc_core.utils import check_format_trans_file

In [14]:
th = pd.read_csv("./S_tahi_sub_2.csv", parse_dates=["date"])
th=th.sort_values("date")
th["month"] = th["date"].dt.month
th["year"]=th["date"].dt.year

In [17]:
gt

        id_user       date  hours id_item  price  qty
0         17850 2010-12-01  08:26  85123A   2.55    6
1         17850 2010-12-01  08:26   71053   3.39    6
2         17850 2010-12-01  08:26  84406B   2.75    8
3         17850 2010-12-01  08:26  84029G   3.39    6
4         17850 2010-12-01  08:26  84029E   3.39    6
5         17850 2010-12-01  08:26   22752   7.65    2
6         17850 2010-12-01  08:26   21730   4.25    6
7         17850 2010-12-01  08:28   22633   1.85    6
8         17850 2010-12-01  08:28   22632   1.85    6
9         13047 2010-12-01  08:34   84879   1.69   32
10        13047 2010-12-01  08:34   22745   2.10    6
11        13047 2010-12-01  08:34   22748   2.10    6
12        13047 2010-12-01  08:34   22749   3.75    8
13        13047 2010-12-01  08:34   22310   1.65    6
14        13047 2010-12-01  08:34   84969   4.25    6
15        13047 2010-12-01  08:34   22623   4.95    3
16        13047 2010-12-01  08:34   22622   9.95    2
17        13047 2010-12-01  08:34   21754   5.95    3
18        13047 2010-12-01  08:34   21755   5.95    3
19        13047 2010-12-01  08:34   21777   7.95    4
20        13047 2010-12-01  08:34   48187   7.95    4
21        13047 2010-12-01  08:34   22960   4.25    6
22        13047 2010-12-01  08:34   22913   4.95    3
23        13047 2010-12-01  08:34   22912   4.95    3
24        13047 2010-12-01  08:34   22914   4.95    3
25        13047 2010-12-01  08:35   21756   5.95    3
26        12583 2010-12-01  08:45   22728   3.75   24
27        12583 2010-12-01  08:45   22727   3.75   24
28        12583 2010-12-01  08:45   22726   3.75   12
29        12583 2010-12-01  08:45   21724   0.85   12
...         ...        ...    ...     ...    ...  ...
307024    15804 2011-12-09  12:31   22726   3.75    8
307025    15804 2011-12-09  12:31   22727   3.75    4
307026    15804 2011-12-09  12:31   16016   0.85   10
307027    15804 2011-12-09  12:31   21916   0.42   24
307028    15804 2011-12-09  12:31   84692   0.42   25
307029    15804 2011-12-09  12:31   84946   1.25   12
307030    15804 2011-12-09  12:31   21684   0.85   12
307031    15804 2011-12-09  12:31   22398   0.39   12
307032    15804 2011-12-09  12:31   23328   3.75    4
307033    15804 2011-12-09  12:31   23145   0.95   12
307034    15804 2011-12-09  12:31   22466   1.95   12
307035    13113 2011-12-09  12:49   22061   2.95    8
307036    13113 2011-12-09  12:49   23275   1.25   24
307037    13113 2011-12-09  12:49   21217   8.95   24
307038    13113 2011-12-09  12:49   20685   7.08   10
307039    12680 2011-12-09  12:50   22631   1.95   12
307040    12680 2011-12-09  12:50   22556   1.65   12
307041    12680 2011-12-09  12:50   22555   1.65   12
307042    12680 2011-12-09  12:50   22728   3.75    4
307043    12680 2011-12-09  12:50   22727   3.75    4
307044    12680 2011-12-09  12:50   22726   3.75    4
307045    12680 2011-12-09  12:50   22730   3.75    4
307046    12680 2011-12-09  12:50   22367   1.95    8
307047    12680 2011-12-09  12:50   22629   1.95   12
307048    12680 2011-12-09  12:50   23256   4.15    4
307049    12680 2011-12-09  12:50   22613   0.85   12
307050    12680 2011-12-09  12:50   22899   2.10    6
307051    12680 2011-12-09  12:50   23254   4.15    4
307052    12680 2011-12-09  12:50   23255   4.15    4
307053    12680 2011-12-09  12:50   22138   4.95    3

[307054 rows x 6 columns]

In [5]:
gt = pd.read_csv("./ground_truth.csv", parse_dates=["date"])

In [6]:
gt

        id_user       date  hours id_item  price  qty
0         17850 2010-12-01  08:26  85123A   2.55    6
1         17850 2010-12-01  08:26   71053   3.39    6
2         17850 2010-12-01  08:26  84406B   2.75    8
3         17850 2010-12-01  08:26  84029G   3.39    6
4         17850 2010-12-01  08:26  84029E   3.39    6
5         17850 2010-12-01  08:26   22752   7.65    2
6         17850 2010-12-01  08:26   21730   4.25    6
7         17850 2010-12-01  08:28   22633   1.85    6
8         17850 2010-12-01  08:28   22632   1.85    6
9         13047 2010-12-01  08:34   84879   1.69   32
10        13047 2010-12-01  08:34   22745   2.10    6
11        13047 2010-12-01  08:34   22748   2.10    6
12        13047 2010-12-01  08:34   22749   3.75    8
13        13047 2010-12-01  08:34   22310   1.65    6
14        13047 2010-12-01  08:34   84969   4.25    6
15        13047 2010-12-01  08:34   22623   4.95    3
16        13047 2010-12-01  08:34   22622   9.95    2
17        13047 2010-12-01  08:34   21754   5.95    3
18        13047 2010-12-01  08:34   21755   5.95    3
19        13047 2010-12-01  08:34   21777   7.95    4
20        13047 2010-12-01  08:34   48187   7.95    4
21        13047 2010-12-01  08:34   22960   4.25    6
22        13047 2010-12-01  08:34   22913   4.95    3
23        13047 2010-12-01  08:34   22912   4.95    3
24        13047 2010-12-01  08:34   22914   4.95    3
25        13047 2010-12-01  08:35   21756   5.95    3
26        12583 2010-12-01  08:45   22728   3.75   24
27        12583 2010-12-01  08:45   22727   3.75   24
28        12583 2010-12-01  08:45   22726   3.75   12
29        12583 2010-12-01  08:45   21724   0.85   12
...         ...        ...    ...     ...    ...  ...
307024    15804 2011-12-09  12:31   22726   3.75    8
307025    15804 2011-12-09  12:31   22727   3.75    4
307026    15804 2011-12-09  12:31   16016   0.85   10
307027    15804 2011-12-09  12:31   21916   0.42   24
307028    15804 2011-12-09  12:31   84692   0.42   25
307029    15804 2011-12-09  12:31   84946   1.25   12
307030    15804 2011-12-09  12:31   21684   0.85   12
307031    15804 2011-12-09  12:31   22398   0.39   12
307032    15804 2011-12-09  12:31   23328   3.75    4
307033    15804 2011-12-09  12:31   23145   0.95   12
307034    15804 2011-12-09  12:31   22466   1.95   12
307035    13113 2011-12-09  12:49   22061   2.95    8
307036    13113 2011-12-09  12:49   23275   1.25   24
307037    13113 2011-12-09  12:49   21217   8.95   24
307038    13113 2011-12-09  12:49   20685   7.08   10
307039    12680 2011-12-09  12:50   22631   1.95   12
307040    12680 2011-12-09  12:50   22556   1.65   12
307041    12680 2011-12-09  12:50   22555   1.65   12
307042    12680 2011-12-09  12:50   22728   3.75    4
307043    12680 2011-12-09  12:50   22727   3.75    4
307044    12680 2011-12-09  12:50   22726   3.75    4
307045    12680 2011-12-09  12:50   22730   3.75    4
307046    12680 2011-12-09  12:50   22367   1.95    8
307047    12680 2011-12-09  12:50   22629   1.95   12
307048    12680 2011-12-09  12:50   23256   4.15    4
307049    12680 2011-12-09  12:50   22613   0.85   12
307050    12680 2011-12-09  12:50   22899   2.10    6
307051    12680 2011-12-09  12:50   23254   4.15    4
307052    12680 2011-12-09  12:50   23255   4.15    4
307053    12680 2011-12-09  12:50   22138   4.95    3

[307054 rows x 6 columns]